import { HostawayReview } from "./types";

export const MOCK_REVIEWS: HostawayReview[] = [
  {
    id: 7453,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Amazing property in the heart of Shoreditch! The apartment was spotless and had everything we needed. Host was very responsive and check-in was seamless.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
      { category: "accuracy", rating: 9 },
      { category: "location", rating: 10 },
    ],
    submittedAt: "2024-12-15 14:30:00",
    guestName: "Sarah Johnson",
    listingName: "2B N1 A - 29 Shoreditch Heights",
    channelName: "Airbnb",
  },
  {
    id: 7454,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Great stay overall. Location is perfect for exploring the area. Only minor issue was the shower pressure, but everything else was excellent.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "accuracy", rating: 8 },
      { category: "location", rating: 10 },
      { category: "value", rating: 9 },
    ],
    submittedAt: "2024-12-10 09:15:00",
    guestName: "Marcus Chen",
    listingName: "1B E2 B - Hackney Loft",
    channelName: "Booking.com",
  },
  {
    id: 7455,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Decent place but had some noise issues from the street at night. Would recommend earplugs for light sleepers. Otherwise, good value for money.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 9 },
      { category: "accuracy", rating: 7 },
      { category: "location", rating: 9 },
      { category: "value", rating: 8 },
    ],
    submittedAt: "2024-12-08 16:45:00",
    guestName: "Emily Roberts",
    listingName: "2B N1 A - 29 Shoreditch Heights",
    channelName: "Airbnb",
  },
  {
    id: 7456,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Absolutely loved our stay! The apartment exceeded our expectations. Modern, clean, and the location couldn't be better. Will definitely be back!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "check_in", rating: 10 },
      { category: "value", rating: 9 },
    ],
    submittedAt: "2024-12-05 11:20:00",
    guestName: "David Martinez",
    listingName: "Studio S3 - Camden Market View",
    channelName: "Direct",
  },
  {
    id: 7457,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Nice apartment but WiFi was unstable during our work calls. Also, no parking nearby which was inconvenient. Otherwise comfortable stay.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 7 },
      { category: "accuracy", rating: 7 },
      { category: "location", rating: 8 },
      { category: "value", rating: 7 },
    ],
    submittedAt: "2024-12-01 08:30:00",
    guestName: "Lisa Anderson",
    listingName: "1B E2 B - Hackney Loft",
    channelName: "Booking.com",
  },
  {
    id: 7458,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Perfect for our family weekend! Kids loved the space and we appreciated the well-equipped kitchen. Great communication from the host team.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "accuracy", rating: 9 },
      { category: "location", rating: 9 },
      { category: "check_in", rating: 10 },
    ],
    submittedAt: "2024-11-28 19:45:00",
    guestName: "James Wilson",
    listingName: "2B N1 A - 29 Shoreditch Heights",
    channelName: "Airbnb",
  },
  {
    id: 7459,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Stylish apartment in a vibrant neighborhood. The bed was incredibly comfortable and amenities were top-notch. Highly recommend!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 9 },
    ],
    submittedAt: "2024-11-25 14:15:00",
    guestName: "Sophie Turner",
    listingName: "Studio S3 - Camden Market View",
    channelName: "Airbnb",
  },
  {
    id: 7460,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Good location but the apartment felt smaller than the photos suggested. Cleanliness was okay but could be better. Heating worked well though.",
    reviewCategory: [
      { category: "cleanliness", rating: 7 },
      { category: "communication", rating: 8 },
      { category: "accuracy", rating: 6 },
      { category: "location", rating: 9 },
      { category: "value", rating: 7 },
    ],
    submittedAt: "2024-11-20 10:30:00",
    guestName: "Robert Kim",
    listingName: "1B E2 B - Hackney Loft",
    channelName: "Vrbo",
  },
  {
    id: 7461,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Exceptional stay from start to finish. The attention to detail in the apartment was impressive. Easy check-in and the host was available when needed.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 9 },
      { category: "check_in", rating: 10 },
      { category: "value", rating: 10 },
    ],
    submittedAt: "2024-11-18 16:00:00",
    guestName: "Anna Kowalski",
    listingName: "2B W1 C - Soho Penthouse",
    channelName: "Direct",
  },
  {
    id: 7462,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "The apartment was clean but quite noisy due to construction nearby. This wasn't mentioned in the listing. Apart from that, good value.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 8 },
      { category: "accuracy", rating: 6 },
      { category: "location", rating: 7 },
      { category: "value", rating: 7 },
    ],
    submittedAt: "2024-11-15 09:45:00",
    guestName: "Michael Brown",
    listingName: "Studio S3 - Camden Market View",
    channelName: "Booking.com",
  },
  {
    id: 7463,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Wonderful experience! The rooftop terrace was a highlight. Everything was exactly as described. Will recommend to friends visiting London.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "check_in", rating: 9 },
    ],
    submittedAt: "2024-11-12 13:20:00",
    guestName: "Jessica Lee",
    listingName: "2B W1 C - Soho Penthouse",
    channelName: "Airbnb",
  },
  {
    id: 7464,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Decent property for the price. Could use some updates to the furniture and better lighting. Location is convenient though.",
    reviewCategory: [
      { category: "cleanliness", rating: 7 },
      { category: "communication", rating: 8 },
      { category: "accuracy", rating: 7 },
      { category: "location", rating: 9 },
      { category: "value", rating: 8 },
    ],
    submittedAt: "2024-11-08 11:10:00",
    guestName: "Tom Harris",
    listingName: "1B E2 B - Hackney Loft",
    channelName: "Airbnb",
  },
  {
    id: 7465,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Outstanding! Best Airbnb we've stayed at in London. Everything from the decor to the amenities was perfect. The host thought of everything!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "check_in", rating: 10 },
      { category: "value", rating: 10 },
    ],
    submittedAt: "2024-11-05 15:30:00",
    guestName: "Rachel Green",
    listingName: "2B W1 C - Soho Penthouse",
    channelName: "Airbnb",
  },
  {
    id: 7466,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Good for a short stay. Bathroom could be cleaner and the kitchen needs better cookware. But bed was comfortable and location was great.",
    reviewCategory: [
      { category: "cleanliness", rating: 7 },
      { category: "communication", rating: 9 },
      { category: "accuracy", rating: 8 },
      { category: "location", rating: 9 },
      { category: "value", rating: 7 },
    ],
    submittedAt: "2024-11-01 10:15:00",
    guestName: "Chris Evans",
    listingName: "Studio S3 - Camden Market View",
    channelName: "Vrbo",
  },
  {
    id: 7467,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview:
      "Lovely apartment with all the essentials. Great for remote work with fast WiFi and a comfortable desk. Would stay again!",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "accuracy", rating: 9 },
      { category: "location", rating: 9 },
      { category: "check_in", rating: 9 },
      { category: "value", rating: 9 },
    ],
    submittedAt: "2024-10-28 12:45:00",
    guestName: "Olivia Martinez",
    listingName: "2B N1 A - 29 Shoreditch Heights",
    channelName: "Direct",
  },
];